version: "3.8"

services:
  web:
    image: mydockerhubusername/my-shopify-app:latest  # Pull latest image
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
