# fly.toml app configuration file generated for syhipping on 2025-03-09T15:47:19+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'syhipping'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'node prisma/seed.js'

[env]
  PORT = '3000'
  SCOPES = 'read_checkouts,read_orders,read_products,read_script_tags,write_checkouts,write_products,write_script_tags'
  SHOPIFY_API_KEY = 'f6fdb2043edc446641f6bce03dae17d9'
  SHOPIFY_APP_URL = 'https://syhipping.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2
