# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65b1344df049d7c1a7a88a605a587a0c"
application_url = "https://gstunc.live/"
embedded = true
name = "shipping-protection"
handle = "shipping-protection-38"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_products,read_script_tags,write_checkouts,write_products,write_script_tags,update_products,read_orders"


[auth]
redirect_urls = [
  "https://gstunc.live/auth/callback",
  "https://gstunc.live/auth/shopify/callback",
  "https://gstunc.live/api/auth/callback"
]

[pos]
embedded = true

[build]
include_config_on_deploy = true
