# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6fdb2043edc446641f6bce03dae17d9"
application_url = "https://syhipping.fly.dev"
embedded = true
name = "shipping-protection"
handle = "shipping-protection-38"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "shipteststore4395.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_products,read_script_tags,write_checkouts,write_products,write_script_tags,read_orders"

[auth]
redirect_urls = [
  "https://syhipping.fly.dev/auth/callback",
  "https://syhipping.fly.dev/auth/shopify/callback",
  "https://syhipping.fly.dev/api/auth/callback"
]

[pos]
embedded = false
